server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: Spring Boot Demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:database_name}
    username: ${SPRING_DATASOURCE_USERNAME:postgre}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e}
